<?php
// header("Refresh:5")
?>
<!doctype html>
<html lang="tr-TR">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<meta http-equiv="content-language" content="tr">
<meta charset="utf-8">
<title>baslik</title>
</head>
<body>
    <?php
    /*
   INNER JOIN   :   MySQL sunucusundaki database icerisinde bulunan herhangi iki veya daha fazla tablonun eslesen degerlerinin birbiri ile iliskilendirilmesi icin kullanilir.
   LEFT  JOIN   :   MySQL sunucusundaki database icerisinde bulunan herhangi iki veya daha fazla tablonun soldaki tabloya gore eslesen degerlerinin birbiri ile iliskilendirilmesi icin kullanilir.
   RIGHT JOIN   :   MySQL sunucusundaki database icerisinde bulunan herhangi iki veya daha fazla tablonun sagdaki tabloya gore eslesen degerlerinin birbiri ile iliskilendirilmesi icin kullanilir.
   NATURAL JOIN :   MySQL sunucusundaki database icerisinde bulunan herhangi iki veya daha fazla tablonun eslesen degerlerinin birbiri ile otomatik iliskilendirilmesi icin kullanilir.
   USING        :   MySQL sunucusundaki database icerisinde bulunan herhangi iki veya daha fazla tablonun birbirleri ile iliskilendirilmesi sirasinda ortak sutun kosulunu tanimlamak veya belirtmek icin kullanilir.
   ON           :   MySQL sunucusundaki database icerisinde bulunan herhangi iki veya daha fazla tablonun birbirleri ile iliskilendirilmesi sirasinda sutun kosulunu tanimlamak veya belirtmek icin kullanilir.
    */
 //CALISMA MANTIGI MYSQLI ILE AYNIDIR FARKLILIK YOK

    ?>
</body>
</html>	